FROM python:3.11

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python -m spacy donload en_core_web_sm

EXPOSE 8501

CMD ["python, "-m", "streamlit", "run", "app_streamlit.py"]
