FROM python:3.11

WORKDIR /app

COPY . .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python -m spacy download en_core_web_sm

ENV FLASK_APP="app_flask.py"


CMD ["python", "-m", "flask", "run", "--host=0.0.0.0"]
